// Emits the colour half of src/tokens.css from the measured palette, so a swatch
// on the canvas and the value the browser paints cannot drift apart.
//
//   node tools/build-tokens.mjs
//
// Only the region between the markers is generated. Everything else in
// tokens.css - type, spacing, radius, control heights, motion, @font-face - is
// hand-written, because none of it is derived from anything and a generator for
// it would be indirection with no source of truth behind it.

import { readFileSync, writeFileSync } from 'node:fs'
import { pathToFileURL } from 'node:url'
import { build } from './palette-report.mjs'

export const DIRECTION = 'petrol'
export const BEGIN_MARKER = '/* >>> generated by tools/build-tokens.mjs - do not edit by hand */'
export const END_MARKER = '/* <<< end generated */'

const fmt = ([L, C, h]) => `oklch(${L} ${C} ${h})`

function declarations(tokens, indent) {
  return Object.entries(tokens)
    .map(([name, value]) => `${indent}--fds-${name}: ${fmt(value.oklch)};`)
    .join('\n')
}

export function renderColourTokens() {
  const { tokens } = build(DIRECTION)
  const light = declarations(tokens.light, '  ')
  const darkNested = declarations(tokens.dark, '    ')
  const dark = declarations(tokens.dark, '  ')

  // Light sits on the bare :root so a token can never exist only inside a media
  // query - the failure where one appearance silently loses its colours. The
  // :not() guard is what lets an explicit light choice win under a dark system,
  // and the two attribute blocks make the toggle authoritative both ways.
  return `
/* Light appearance. Every token is declared here; the blocks below only
   override values, never introduce names. */
:root {
${light}
}

/* The system preference, unless the document has explicitly asked for light. */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${darkNested}
  }
}

/* An explicit choice wins in both directions. */
:root[data-theme='dark'] {
${dark}
}

:root[data-theme='light'] {
${light}
}
`
}

function splice(source) {
  const start = source.indexOf(BEGIN_MARKER)
  const end = source.indexOf(END_MARKER)
  if (start === -1 || end === -1) {
    throw new Error('src/tokens.css is missing the generated colour markers')
  }
  return source.slice(0, start + BEGIN_MARKER.length) + renderColourTokens() + source.slice(end)
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const path = new URL('../src/tokens.css', import.meta.url)
  const before = readFileSync(path, 'utf8')
  const after = splice(before)
  writeFileSync(path, after, 'utf8')
  console.log(
    after === before
      ? 'src/tokens.css already current'
      : `src/tokens.css updated from the ${DIRECTION} palette`,
  )
}
